UCLALibrary/ftva-website-nuxt

gql/queries/FTVAEventDetail.gql
Connected to [APPS-2854](https://uclalibrary.atlassian.net/browse/APPS-2854)
https://deploy-preview-11--test-ftva.netlify.app/events/la-r%C3%A9gion-centrale-03-08-24
[APPS-2854]: https://uclalibrary.atlassian.net/browse/APPS-2854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: APPS-2854 Page ftvaEvent query to title: eventTitle

.gitignore, pages/events/[slug].vue
Connected to [APPS-2842](https://jira.library.ucla.edu/browse/APPS-2842)
**Page/Pages Created/updated:** [slug].vue 
**Notes:**
We originally thought this was a cardMeta component issue, but on inspection it was because the grid-layout forces the height of the elements in the grid to match. I reduced the sidebar height on larger screens to prevent this, ~~but it means that the sidebar content will scroll behind the bottom section content instead of stopping above it.~~ edit: I couldn't stand the look of the scroll-behind solution so I have added some inline styles powered by refs to dynamically add bottom-padding to prevent this.  
This took me 8ish hours to build this.
**Checklist:**
-   [ ] I double checked it looks …
=> fix: APPS-2842 grid layout causing space at top of layout

pages/events/[slug].vue
Connected to [APPS-2844](https://jira.library.ucla.edu/browse/APPS-2844)
**Page/Pages Created/updated:** [slug].vue 
**Notes:**
During initial page review [Axa asked that we set the page max-width to 1160px](https://uclalibrary.slack.com/archives/C014BPS0YBX/p1722031120220339?thread_ts=1722028832.405809&cid=C014BPS0YBX)
I noticed during testing carousel style bugs earlier that the wider width prevents some of the carousel issues, so Id like to go ahead and make this change before changing carousel styles further.
**Checklist:**
-   [ ] I completed any required mobile breakpoint styling
-   [ ] I completed any required hover state styling
-   [ ] I …
=> fix: APPS-2844 maxwidth, which helps fix most carousel issues

gql/queries/FTVAEventDetail.gql
Connected to [APPS-2874](https://jira.library.ucla.edu/browse/APPS-2874)
https://deploy-preview-17--test-ftva.netlify.app/events/la-r%C3%A9gion-centrale-03-08-24
The link was wrong it doubled event
`/events/events/high-noon-10-20-23`
Acceptance Criteria
[APPS-2874]: https://uclalibrary.atlassian.net/browse/APPS-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: APPS-2874  Page SectionTeaserCard Link

pages/events/[slug].vue
Connected to [APPS-2869](https://jira.library.ucla.edu/browse/APPS-2869)
**Page updated:** /events/[slug].vue
**Notes:**
- Removed fixed height value set on ResponsiveVideo sizer element; this reduced excess negative space underneath embedded videos
**Before:**
**After:**
**Checklist:**
-   [x] I requested a PR review from dev team
[APPS-2869]: https://uclalibrary.atlassian.net/browse/APPS-2869?atlOrigin=eyJpIj …
=> fix: APPS-2869 Remove fixed height on embedded video sizer

package.json, pages/events/[slug].vue, pnpm-lock.yaml
This PR 
+ updates the library components to version 3.6.4
+ adds title to the Navbreadcrumb component
+ add the `vite.config.ts` update 
```
rollupOptions: {
external: ['vue', 'vue-router', 'pinia'],
...
```
=> chore: Update library components to version 3.6.4

gql/queries/FTVAEventDetail.gql, pages/events/[slug].vue
Connected to [APPS-2878](https://jira.library.ucla.edu/browse/APPS-2878)
**Page updated:** /events/[slug].vue
**Notes:**
- Updated query to fetch upcoming events
- Refactored computed property for parsing event series
- Updated template to reference parsed series array
**Before:**
**After:**
**Checklist:**
[APPS-2878]: …
=> fix: APPS-2878 Show Only Upcoming Events in a Series

gql/queries/FTVAEventList.gql, gql/queries/FTVAEventSeriesList.gql
Connected to [APPS-2884](https://jira.library.ucla.edu/browse/APPS-2884)
**Notes:**
- Production build sometimes fails on sample event listing page; this PR temporarily resolves this by disabling the image query field in the EventList and EventSeriesList `gql` files; see ticket for more details
**Checklist:**
-   [x] I requested a PR review from the Dev team
[APPS-2884]: …
=> fix: APPS-2884 Temporarily disable image query

cypress/e2e/eventDetailPage.cy.js, cypress/e2e/homepage.cy.js, gql/queries/FTVAEventDetail.gql, pages/events/[slug].vue
Connected to [APPS-2870](https://jira.library.ucla.edu/browse/APPS-2870) && [PR](https://github.com/UCLALibrary/ucla-library-website-components/pull/582)
1. This is the Nuxt part of this ticket to move the guestSpeaker into the CardMeta and the textDescription into a RichText component
2. This PR also contains changes to the Cypress tests to not take a screenshot of the home page and names the screenshot on the eventDetails page
**Checklist:**
[APPS-2870]: https://uclalibrary.atlassian.net/browse/APPS-2870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: APPS-2870 Page TextDescription and GuestSpeakerre-arranged to fix text truncation problem

pages/events/[slug].vue
Connected to [APPS-2880](https://jira.library.ucla.edu/browse/APPS-2880)
**Notes:**
The image at the top of the page should have a ratio of 1 (tall) to 2.31 (long), which works out to 1/2.31 = ~.43103
Responsive Image component expects this as a percentage so the prop is passed as 43.103.
Once that was fixed, it was noticed that the blue banner at the top of the screen needed an aspect ratio as well, so that was set. 
I also fixed the issue with the pagelayout rendering the credit text whether or not there was any.
UX reported that the carousel should be changed to the same aspect ratio, so I added that to the APPS-2844
It took me 4 hours to build & test this.
**Checklist:**
-   [X] I double checked it looks like the …
=> fix: set aspect ratio for images

pages/events/[slug].vue
Connected to [APPS-2893](https://jira.library.ucla.edu/browse/APPS-2893)
**Page/Pages Created/updated:** slug.vue from #{issue number}
**Notes:**
The blue element at the top of page was recently made responsive, but we did not set a max-height for large screens. This PR fixes that. 
This took me .5 hours to build this.
**Checklist:**
-   [X] I completed any required mobile breakpoint styling
-   [ ] I completed any required hover state styling
-   [X] UX has reviewed this PR
[APPS-2893]: …
=> fix: APPS-2893 set max height blue box for large screens

package.json, pages/events/[slug].vue, pnpm-lock.yaml
Connected to [APPS-2918](https://jira.library.ucla.edu/browse/APPS-2918)
[APPS-2918]: https://uclalibrary.atlassian.net/browse/APPS-2918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Upcoming Events card responsiveness, max-width work and background color FTVA variation in SectionWrapper

assets/styles/global.scss, cypress/e2e/eventSeriesDetailPage.cy.js, gql/queries/FTVAEventSeriesDetail.gql, package.json, pages/events/[slug].vue, pages/series/[slug].vue, pages/series/index.vue, pnpm-lock.yaml
Connected to [APPS-2910](https://jira.library.ucla.edu/browse/APPS-2910)
**Page/Pages Created/updated:** [slug].vue 
**Notes:**
Styles:
For the first page I added most styles directly to the page, including some global variables.
Because we are reusing a lot of these styles across pages, I have moved reused styles to global.scss to prevent duplication and keep things DRY
MOBILE:
The mockups for this page show complex behavior for the sidebar content (the previously sticky sidebar needs to split into 2 distinct content blocks and slot into 2 different areas in the column). This work is not 100% done, and will be continued in this ticket https://uclalibrary.atlassian.net/browse/APPS-2946
BLOCKCARDTHREECOLUMN: 
Fixed in this [commit](https://github.com/UCLALibrary/ftva-website/nuxt/pull/39/co …
=> feat: APPS-2910 assemble event series page

cypress/e2e/blogArticlePage.cy.js, gql/queries/FTVAArticleDetail.gql, package.json, pages/blog/[slug].vue, pages/events/[slug].vue, pnpm-lock.yaml, utils/socialList.js
Connected to [APPS-2955](https://jira.library.ucla.edu/browse/APPS-2955)
**Page/Pages Created/updated:** /blog/[slug].vue from APPS-2955
**Notes:**
- Updated package to latest components
- Added cypress test for blog page
- Added sidebar to blog page
- Added Share Dropdown Button and new CardMeta dateCreated data
- Added a computed method to parse images from recentPosts data
- Slight edit to FTVAArticleDetail.gql to return 4 items instead of 3, as well as computed method to parse current article out of data
- Slight edit to categories logic to reduce # of lines (this is a matter of opinion and we can revert this if we want the longer -but possibly more readable- version)
- Tested and removed some junk data from carousel (also removed same junk data from /events/[slug].vue)
- Tweaked …
=> feat: APPS-2955 remaining components 

gql/queries/EventDetail.gql, gql/queries/FTVAEventDetail.gql, gql/queries/FTVAEventList.gql, gql/queries/FTVAEventSeriesDetail.gql, gql/queries/FTVAEventSeriesList.gql
Connected to [APPS-2970](https://jira.library.ucla.edu/browse/APPS-2970)
**Page/Pages Created/updated:** {filename}.vue from #{issue number}
**Notes:**
In progress
Axa met with me Friday (10/4) to discuss and had already done some testing. She indicated (and the library-website-nuxt site agrees) that we need to use @formatDateTime functions to format the dateTimes to the correct timezone. Otherwise, netlify's server times will dictate time zone on production, leading to mismatches and bugs. 
This took me 2ish hours so far to build this.
**Checklist:**
- ~~[ ] I double checked it looks like the designs~~
- ~~[ ] I completed any required mobile breakpoint styling~~
- ~~[ ] I completed any required hover state styling~~
- …
=> fix: APPS-2970 dateTimes incorrect in ftva

package.json, pages/events/[slug].vue, pages/series/[slug].vue, pnpm-lock.yaml
Connected to [APPS-2998](https://jira.library.ucla.edu/browse/APPS-2998)
**Pages Updated:**
- pages/events/[slug].vue
- pages/series/[slug].vue
**Notes:**
- Updated library component package from `3.27.0` to `3.28.0` to include FTVA variants of MediaGallery components
- Add `inline=true` to inline use cases of MediaGalleryNewLightbox
<br>
**Deploy Previews:**
- Event page (Inline): https://deploy-preview-49--test-ftva.netlify.app/events/la-r%C3%A9gion-centrale-03-08-24/
- Series page (Inline): https://deploy-preview-49--test-ftva.netlify.app/series/step-up-series
- Blog page (Lightbox): https://deploy-preview-49--test-ftva.netlify.app/blog/test-tom-reeds-for-members-only-black-perspectives-on-local-l-a-tv
<br>
**Local Previews:**
*Event page - Inline Carousel:*
<br>
*Series page - Inline …
=> fix: APPS-2998 Update inline carousels with new prop

cypress/e2e/collectionDetailPage.cy.js, package.json, pages/blog/[slug].vue, pages/collections/[slug].vue, pages/collections/index.vue, pages/series/[slug].vue, pnpm-lock.yaml
Connected to [APPS-2997](https://jira.library.ucla.edu/browse/APPS-2997)
**Page/Pages Created/updated:** /collections/[slug].vue, /collections/index.vue from #{APPS-2997}
**Notes:**
- updated tokens and component packages to latest
- updated page to use carousel inline
- created computed functions to parse data for related collections section, also to set defaults for sectionHeader, viewAllLink text and uri
- created computed functions for infoBlock data and rendered it with new CallToAction blocks 
- added a cypress test
- removed old un-needed code for sidebar from /series/slug page
- made sure carousel is inline in blog page
Questions for team:
Growing Tech Debt
There are some repeated bits of code starting to grow such as logic for carousel / image at top of page and styles for that …
=> feat: APPS-2997 finish collection detail page

gql/queries/FTVAEventSeriesDetail.gql
Connected to [APPS-2968](https://jira.library.ucla.edu/browse/APPS-2968)
BEFORE (sort by ASC order)
AFTER (sort by DESC order)
[APPS-2968]: https://uclalibrary.atlassian.net/browse/APPS-2968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: APPS-2968   EventSeriesDetail - Sort past events by DESC order

pages/series/[slug].vue
Connected to [APPS-2965](https://jira.library.ucla.edu/browse/APPS-2965)
**Page Updated:** pages/series/[slug].vue
**Notes:**
- Updated parent title from `Screening Series` to `Series`
**Checklist:**
-   [x] I requested a PR review from the Dev team
[APPS-2965]: https://uclalibrary.atlassian.net/browse/APPS-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: APPS-2965 Update series page breadcrumb parent title

package.json, pages/collections/[slug].vue, pnpm-lock.yaml
Connected to [APPS-3007](https://jira.library.ucla.edu/browse/APPS-3007)
**Page Updated:** /pages/collections/[slug].vue
**Notes:**
- Update icon lookup with ftva-external-link name
- Update component package from `3.31.6`
https://deploy-preview-59--test-ftva.netlify.app/collections/test-get-used-to-it/
**Checklist:**
-   [x] I have requested a PR review from the Dev team
[APPS-3007]: …
=> feat: APPS-3007 Add BlockInfo external icon

assets/styles/slug-pages.scss, pages/blog/[slug].vue, pages/collections/[slug].vue, pages/events/[slug].vue, pages/series/[slug].vue
Connected to [APPS-3010](https://jira.library.ucla.edu/browse/APPS-3010)
**Pages Updated:**
- /pages/blog/[slug].vue
- /pages/collection/[slug].vue
- /pages/events/[slug].vue
- /pages/series/[slug].vue
**Notes:**
- Consolidate similar slug page styles into a single .scss file for easy maintenance
**Previews:**
- Blog: https://deploy-preview-65--test-ftva.netlify.app/blog/test-tom-reeds-for-members-only-black-perspectives-on-local-l-a-tv
- Collection: https://deploy-preview-65--test-ftva.netlify.app/collections/test-get-used-to-it/
- Events: https://deploy-preview-65--test-ftva.netlify.app/events/the-pink-cloud-shorts-03-02-24/
- Series: https://deploy-preview-65--test-ftva.netlify.app/series/step-up-series
**Checklist:**
-   [x] I have …
=> feat: APPS-3010 Consolidate slug page styles

composables/useContentIndexer.js, gql/queries/FTVAArticleDetail.gql, gql/queries/FTVACollectionDetail.gql, gql/queries/FTVAEventDetail.gql, gql/queries/FTVAEventSeriesDetail.gql, pages/blog/[slug].vue, pages/collections/[slug].vue, pages/events/[slug].vue, pages/series/[slug].vue
Connected to [APPS-3023](https://jira.library.ucla.edu/browse/APPS-3023)
Create composable and add it to all slug pages
**Notes:**
1.  `composables/useContentIndexer.js`
+ Add a composable that 
```js
Checks the page slug
Calls ES (Elastic Search)
Checks if the document exists in ES
if the document already exists
it overwrites/replaces it in the index
if the document doesn't exist
it adds it to the index
```
3. `pages/events/[slug].vue`
+ Adds the composable to the page
+ Runs the composable function to index the main data on page
4. `pages/series/[slug].vue`
+ Adds the composable to the page
+ Runs the composable function to index the main data on page
5. `pages/collections/[slug].vue`
+ Adds the composable to the page
+ Runs the composable function to index the main data on page
6. …
=> feat: APPS-3023   Create composable useContentIndexer to index craft data used on all routes for FTVA

composables/useIndexAggregator.js, gql/queries/FTVAEventDetail.gql, gql/queries/FTVAEventSeriesDetail.gql, package.json, pages/events/[slug].vue, pages/events/index.vue, pages/series/[slug].vue, pnpm-lock.yaml
Connected to [APPS-3054](https://jira.library.ucla.edu/browse/APPS-3054)
**Page Updated:** 
- pages/events/[slug].vue
- pages/events/index.vue
- pages/series/[slug].vue
**Notes:**
- Updated event query and aggregator composable to account for two sets of filters: Event Type and Screening Format
- Created/updated computed properties to parse tagLabels from the new filters
**Previews:**
_Event Detail_
_Series Detail_
**Checklist:**
-   ~~[ ] I added notes above about how long …
=> fix: APPS-3054 Update Queries, Composable, Logic for Event filters

pages/events/[slug].vue, pages/series/[slug].vue, utils/getEventFilterLabels.js
Connected to [APPS-3065](https://jira.library.ucla.edu/browse/APPS-3065)
**Page Updated:** 
- pages/events/[slug].vue
- pages/series/[slug].vue
**Notes:**
- Extracted repeating/reused logic for parsing tagLabels into a utility function.
**Previews:**
- https://deploy-preview-69--test-ftva.netlify.app/events/the-pink-cloud-shorts-03-02-24/
- https://deploy-preview-69--test-ftva.netlify.app/series/the-films-of-michael-snow
**Checklist:**
-   ~~[ ] I added notes above about how …
=> fix: APPS-3065 Refactor TagLabels Parsing Logic

gql/queries/FTVAEventSeriesList.gql, package.json, pages/series/index.vue, pnpm-lock.yaml
Connected to [APPS-3052](https://jira.library.ucla.edu/browse/APPS-3052)
https://deploy-preview-75--test-ftva.netlify.app/series/
Single Page GQL added to repo and used on `/series/index.vue` and displayed in the template with page level css. 
**Notes**
1. **`pages/series/index.vue`**
+ Adds a max width to the Section Summary at the top of the page to match the design styles.
```
:deep(.section-summary) {
max-width: 687px;
}
```
+ `pages/series/index.vue`
+ Adds a margin at the bottom of the Tab Toggle
```
:deep(.tab-list .tab-list-header) {
margin-bottom: 50px;
}
```
2. **`FTVAEventSeriesDetail.gql`**
```
query FTVAEventSeriesList {
entry(section: ["ftvaListingEventSeries"]) {
id
typeHandle
sectionHandle
titleGeneral
summary
}
}
```
[APPS-3052]: …
=> feat: APPS-3052 Update ftvaEventSeries query

plugins/vuetify.ts
Connected to [APPS-3088](https://jira.library.ucla.edu/browse/APPS-3088)
**Notes:**
Updated vuetify.ts configuration to import more Vuetify components, which are used as part of the Calendar
**Checklist:**
[APPS-3088]: https://uclalibrary.atlassian.net/browse/APPS-3088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: APPS-3088 add vuetify components for Calendar

gql/queries/FTVAEventList.gql, pages/events/index.vue
Connected to [APPS-3050](https://jira.library.ucla.edu/browse/APPS-3050)
**Page/Pages Created/updated:** /events/index.vue & GQL
**Notes:**
I added the query to the existing query for the event listing page. I displayed the text in the page to verify it was there, but it has not been formatted or styled in any way yet. 
This took me 5 hours to build & test this.
**Checklist:**
-   ~~[] I double checked it looks like the designs~~
-   [ ] I assigned …
=> feat: APPS-3050 Add a new gql query on the page for title, summary

composables/useEventSeriesListSearchFilter.js
Connected to [APPS-3114](https://jira.library.ucla.edu/browse/APPS-3114)
Adds the ongoing records
[APPS-3114]: https://uclalibrary.atlassian.net/browse/APPS-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: APPS-3114   Add ongoing to the current and ongoing query on eventSeries page

package.json, pages/collections/[slug].vue, pnpm-lock.yaml
Connected to [APPS-3044](https://jira.library.ucla.edu/browse/APPS-3044)
**Page updated:** /pages/collections/[slug].vue
https://deploy-preview-91--test-ftva.netlify.app/collections/test-get-used-to-it/
**Notes:**
- Stripped out image tags in rich text description used for collection card byline
- Fixed CSS to remove overall text overflow in the collection cards
**Local Previews:**
_Before_
_After_
**Checklist:**
-   [x] UX has reviewed this PR …
=> fix: APPS-3044 Remove image tags

gql/queries/FTVALARebellionFilmmakersDetail.gql, pages/collections/la-rebellion/filmmakers/[slug].vue
Connected to [APPS-3092](https://jira.library.ucla.edu/browse/APPS-3092)
**Page/Pages Created/updated:** /collections/la-rebellion/filmmakers/[slug].vue from #{APPS-3092}
**Notes:**
Created & Tested GQL query on 'test-person' in test-craft, worked fine.
Query does not yet work in production but plans to migrate before the page is due.
This took me 8ish hours to build this.
I spent 4ish hours Tuesday researching & attempting to get relatedEntries in craft without success, however Axa was able to reformat the data so that this became unnecessary. I would still like to understand that later. 
**Checklist:** …
=> feat: Apps-3092 gql LA rebellion

pages/events/index.vue
Connected to [APPS-3084](https://jira.library.ucla.edu/browse/APPS-3084)
**Page updated:** /pages/events/index.vue
**Notes:**
- Make date and event filters and pills sticky on mobile when user scrolls
- Remove filters' stickiness at the bottom of the page (mobile)
- Additional fixes/updates:
- Remove page summary field/content (per UX)
- Display pills on desktop when events are filtered (per UX)
- Clear pills bar/row when filters are emptied
- Update desktop filter button heights to match tab-toggle
- Add class/styling for no-data-found text on mobile
**Checklist:**
- …
=> fix: APPS-3084 Make date and event filters sticky

composables/useArticlesListSearch.js, pages/blog/index.vue
Connected to [APPS-3109](https://jira.library.ucla.edu/browse/APPS-3109)
**Page updated:** /pages/blog/index.vue
https://deploy-preview-97--test-ftva.netlify.app/blog
**Notes:**
- Created composable to fetch Articles list from ES
- Tested composable output (_See console_)
**Checklist:**
[APPS-3109]: https://uclalibrary.atlassian.net/browse/APPS-3109?atlOrigin=eyJp …
=> feat: APPS-3109 Articles List ES query composable

package.json, pages/collections/la-rebellion/filmmakers/[slug].vue, pnpm-lock.yaml
Connected to [APPS-3162](https://jira.library.ucla.edu/browse/APPS-3162)
**Page/Pages Created/updated:** /collections/la-rebellion/filmmakers/[slug].vue from #APPS-3162
**Notes:**
Replaced the old StaffSubjectLibrarian specific component with the new table component
https://deploy-preview-111--test-ftva.netlify.app/collections/la-rebellion/filmmakers/test-person?preview=true
Sidenote: I noticed the column headers on the table were askew ([even before refactor](https://deploy-preview-110--test-ftva.netlify.app/collections/la-rebellion/filmmakers/test-person)), so I will create a ticket to fix those at the component level. The test data in storybook didn't reveal this issue since the column data I used was too uniform! 
This took me 2ish hours to build this.
**Checklist:** …
=> chore: APPS-3162 Replace SectionStaffSubjectLibrarian component with new TableComponent

gql/fragments/collections/AllFtvaFpb.gql, nuxt.config.ts
Updates the AllFtvaFpb query to get rid of the associatedCards Flexible Block that we are replacing with CardWithImage.
We are ONLY removing the associatedCards Flexible Block in this PR so that the Craft PR: [fix: Replace Associated Topics Card flexible block with Flexible Card](https://github.com/UCLALibrary/craftcms/pull/306/files) will not break.
The CardWithImage Flexible Block will be added in a separate PR.
=> fix: update allFtvaFpb query to get rid of the associatedCards Flexible Block

assets/styles/slug-pages.scss, package.json, pages/events/[slug].vue, pages/series/[slug].vue, pnpm-lock.yaml
Connected to [APPS-3231](https://jira.library.ucla.edu/browse/APPS-3231)
**Pages Updated:** 
- /pages/events/[slug].vue
- /pages/series/[slug].vue
**Notes:**
- Updated component library to `3.56.0`
- Refactored `BlockInfo` component on Event and Series slug pages
- Refactored component CSS to shared slug stylesheet.
**Previews:**
- Event slug:
- Before refactor: https://deploy-preview-113--test-ftva.netlify.app/events/step-up-2-07-07-25/
- After: https://deploy-preview-116--test-ftva.netlify.app/events/step-up-2-07-07-25/
- Series slug:
- Before refactor: https://deploy-preview-113--test-ftva.netlify.app/series/step-into-possibilities/
- After: https://deploy-preview-116--test-ftva.netlify.app/series/step-into-possibilities/
**Checklist:**
-   [x] I added github label for semantic …
=> feat: APPS-3231 Refactor BlockInfo on slug pages

pages/[...slug].vue
Connected to [APPS-3248](https://jira.library.ucla.edu/browse/APPS-3248)
**Page Updated:** /pages/[...slug].vue
**Notes:**
- When FlexibleBlocks is wrapped by another component that also uses the SectionWrapper component (such as TwoColLayoutWStickySidebar on the General Content template page), `top-level`--a computed CSS class from SectionWrapper--is not applied to the SectionWrapper elements/tags in the various flexible blocks. `top-level` appears to be needed for specific spacing styles to be applied to the blocks. Without it, the blocks have no spacing between them.
- Current solution is to apply the missing styles directly at the page level
- A second option is to remove the parent component, which I've opted not to do here
- Reorganized layout because placing the page-anchor inside …
=> fix: APPS-3248 Add spacing between Flexible Blocks

package.json, plugins/vuetify.ts, pnpm-lock.yaml
Connected to [APPS-3265](https://jira.library.ucla.edu/browse/APPS-3265)
**Notes:**
Companion PR to [similar update of Vuetify styles/config clean up in the component library](https://github.com/UCLALibrary/ucla-library-website-components/pull/718).
This task removes all of the MaterialDesign icon styles, but minimally reduces the amount of Vuetify styles. See screenshots below. Still unclear if this will significantly decrease the overall CSS load.
Vuetify's calendar component depends on several other components, though not all of the subcomponents' styles are imported. 
- Updated Vuetify plugin
- Removed Vuetify styles import
- Removed Material Design icon import
- Uninstalled `mdi/font` package
- Updated Nuxt Modules to `1.2.2`
- Verified BaseCalendar instance unaffected
- Before: …
=> fix: APPS 3265 Update Vuetify config in FTVA Nuxt

gql/queries/FTVACollectionTypeListing.gql, nuxt.config.ts, pages/collections/motion-picture/index.vue
Connected to [APPS-3290](https://jira.library.ucla.edu/browse/APPS-3290)
**Pages Created:** /pages/collections/motion-picture.vue
**Preview Routes:**
- Motion Picture: https://deploy-preview-135--test-ftva.netlify.app/collections/motion-picture
- Television: https://deploy-preview-135--test-ftva.netlify.app/collections/television
- Watch Listen Online: https://deploy-preview-135--test-ftva.netlify.app/collections/watch-listen-online
**Notes:**
- Added GQL query for Collections Listing singles
- Setup route aliases
- Basic page setup: useHead, preview logic, raw data for testing
**Checklist:**
-   ~~[ ] I completed any required mobile …
=> feat: APPS-3290 Add CollectionsListingType GQL

composables/useCollectionListSearch.js, gql/queries/FTVACollectionTypeListing.gql, pages/collections/motion-picture/index.vue
Connected to [APPS-3301](https://jira.library.ucla.edu/browse/APPS-3301)
**Page Updated:** /pages/collections/motion-picture/index.vue
**Notes:**
- Setup new composable to fetch collectionType data for Collection Listing Type template from ElasticSearch
- Tested composable output (including output for user interaction with browse-by-alphabet scenario):
- Motion Picture: https://deploy-preview-143--test-ftva.netlify.app/collections/motion-picture
- Television: https://deploy-preview-143--test-ftva.netlify.app/collections/television
- Watch and Listen Online: https://deploy-preview-143--test-ftva.netlify.app/collections/watch-listen-online
- Removed collectionType query from gql 
- **Testing code will be cleaned up (renamed, refactored, etc...) for page assembly**
**Checklist:**
-   [x] I …
=> feat: APPS-3301 Add CollectionListing composable

pages/collections/[collectionSlug]/[slug].vue
Connected to [APPS-3324](https://jira.library.ucla.edu/browse/APPS-3324)
**Page updated:** /collections/[collectionSlug]/[slug].vue
**Notes:**
- Replaced temporary videoEmbed code with VideoEmbed component after data fix in Craft
**Checklist:**
[APPS-3324]: https://uclalibrary.atlassian.net/browse/APPS-3324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> fix: APPS-3324 Restore VideoEmbed element after Craft fix

components/BasicCollection.vue
**Notes:**
A temporary fix to prevent page render errors when InfoBlock data is not formed the way we expect.
Created https://uclalibrary.atlassian.net/browse/APPS-3326 to capture more robust requirements for supporting new type of InfoBlock
=> fix: render basicCollections without infoblock text data

components/StorytellingCollection.vue, cypress/e2e/collectionItemDetailPage.cy.js, gql/fragments/BlockCardWithImageFragment.gql, gql/fragments/collections/AllFtvaFpb.gql, gql/queries/FTVACollectionStory.gql, pages/collections/[slug].vue, pages/collections/la-rebellion/index.vue
Connected to [APPS-3315](https://jira.library.ucla.edu/browse/APPS-3315)
**Page Created:** /pages/collections/la-rebellion/index.vue
**Notes:**
- Created query for `ftvaCollectionStory` type
- Updated ~~FlexibleBlocks query file~~ BlockCardWithImage fragment with field for CardWithImage block styling option
- Setup route aliases
- Basic page setup: useHead, preview logic, raw data for testing
- Deleted StoryTelling component; updated layout choice logic in `collections/[slug].vue`
**Preview:**
- https://deploy-preview-155--test-ftva.netlify.app/collections/la-rebellion
- https://deploy-preview-155--test-ftva.netlify.app/collections/in-the-life
-  ~~No current entry for `In The Life` in the new collection type, so the collection is still using the default/basic template~~
**Checklist:**
- …
=> feat: APPS-3315 Create Storytelling template GraphQL

composables/useFilmmakersListSearch.js, gql/queries/FTVALARebellionFilmmakersList.gql, pages/blog/index.vue, pages/collections/la-rebellion/filmmakers/index.vue
Connected to [APPS-3095](https://jira.library.ucla.edu/browse/APPS-3095), [APPS-3097](https://jira.library.ucla.edu/browse/APPS-3097)
**Page updated:** /pages/collections/la-rebellion/filmmaker/index.vue
**Notes:**
- Update graphQL file to only return single entry content
- Set up composable for LA Rebellion Filmmaker Listings data from ElasticSearch
- Tested composable output
**Preview:** https://deploy-preview-183--test-ftva.netlify.app/collections/la-rebellion/filmmakers/
**Checklist:**
-   ~~[ ] I added notes above …
=> feat: APPS-3097 Add Filmmakers Listing composable

pages/collections/[collectionSlug]/[slug].vue
Connected to [APPS-3283](https://jira.library.ucla.edu/browse/APPS-3283)
**Page/Pages Created/updated:** collections/[collectionSlug]/slug.vue
**Notes:**
I only commented out the collection group lines because Axa specified commenting them out and not deleting them. 
This took me 1 hours to build this.
**Photos:** 
Before:
After: 
**Link:**
https://deploy-preview-190--test-ftva.netlify.app/collections/ktla-newsfilm-collection/senator-john-f-kennedy-gives-press-conference-in-los-angeles/
**Checklist:**
-   [x] I completed any required hover state styling
-   [x] I added …
=> chore: APPS-3283 remove collection group

components/ListOfItemsCollection.vue, composables/useMobileOnlyInfiniteScroll.ts, composables/usePaginationScroll.ts, error.vue, pages/blog/index.vue, pages/collections/motion-picture/index.vue, pages/search.vue, pages/series/index.vue
Connected to [APPS-3212](https://jira.library.ucla.edu/browse/APPS-3212)
**Composable Created:** composables/usePaginationScroll.ts
**Page/Pages Created/updated:** 
/blog/index.vue 
/components/ListOfItemsCollection.vue
/search.vue
/series/index.vue
/collections/motion-picture/index.vue
**Notes:**
🐞 What was happening:  when clicking a pagination link on the last page of pagination, the website was attempting to return to the same position on the page. However, since there are fewer items on the last page, it was jumping all the way to the bottom of the page instead.  see the old behavior here for comparison  https://deploy-preview-185--test-ftva.netlify.app/blog/  
🛠️ What we changed: When a pagination button is clicked, the page will jump to the top of the section instead.  
**Time …
=> fix: APPS-3212 pagination skipping on last page on desktop

gql/queries/FTVACollectionTypeListing.gql, gql/queries/FTVAEventSeriesList.gql, pages/archive-research-study-center/index.vue, pages/blog/index.vue, pages/collections/la-rebellion/filmmakers/index.vue, pages/collections/motion-picture/index.vue, pages/series/index.vue
Connected to [APPS-3180](https://jira.library.ucla.edu/browse/APPS-3180)
**Page/Pages Created/updated:** 
- archive-research-study-center/index.vue
- blog/index.vue
- collections/la-rebellion/filmmakers/index.vue
- collections/motion-picture/index.vue
- series/index.vue
**Notes:**
This adds the DisplaySummary logic to the page.summary display. The logic has been removed from ARSC page because it is not using the page summary to render the information. None of the UX/UI has been changed as a result of these additions. To test this, go into craft and toggle the `Display Summary` field on the single pages. When it is `no` the summary will not appear for each of these pages, if it is `yes` it will appear. 
**Links:**
https://deploy-preview-193--test-ftva.netlify.app/collections/motion-picture …
=> feat: APPS-3180 add display summary logic

pages/archive-research-study-center/index.vue, pages/collections/la-rebellion/filmography/index.vue, pages/collections/motion-picture/index.vue
Connected to [APPS-3402](https://jira.library.ucla.edu/browse/APPS-3402)
**Page/Pages Created/updated:** /collections/motion-picture/index.vue from #APPS-3402
**Notes:**
The issue seems to be with trailing '/' 's in the urls once deployed. This caused the `routeNameToSectionMap` object to fail when the urls didn't match (`/collections/motion-picture` was failing to match `/collections/motion-picture/`).
Because some urls have the trailing slash and some don't I simply added both routes to the route map. 
I also made the same change to the archive study research center & the filmography route, which used the same pattern.
It took me about 6 hours to troubleshoot and fix this issue.
**Checklist:**
-   ~~[ ] I double …
=> fix: APPS-3402 motion-picture collection page will not load from search results link

pages/collections/la-rebellion/filmmakers/index.vue
Connected to [APPS-3435](https://jira.library.ucla.edu/browse/APPS-3435)
**Page/Pages Created/updated:** /collections/la-rebellion/filmmakers/index.vue
**Notes:**
*Caveat: Currently, anyone without a last name will be sorted to the bottom of the list when using last name sorts.  (Like https://test-craft.library.ucla.edu/admin/entries/ftvaLARebellionIndividual/3474661-darin-scott appears out of order, but really has no last name entered in craft). UX is aware of this limitation and has approved it. I believe the intention is that they will use this on production to identify entries that need data re-formatted.
This took me 3 hours to build & test this.
**Checklist:**
- …
=> feat: APPS-3435 add 2 new sort options to filmmakers page

components/BasicCollection.vue, gql/queries/FTVACollectionDetail.gql
Connected to [APPS-3448](https://jira.library.ucla.edu/browse/APPS-3448)
**Notes:**
An earlier patch to prevent contact info blocks from crashing this page failed to include the [0] for the array item, which instead caused infoblocks to never appear. 
I also noticed that the icon names coming from craft had been changed, and a heading had been added to some data, so I added support for that. 
I honestly don't recall how long this took as it was off and on between other tasks, probably 2-3 hours
**Checklist:**
-   [X] I completed any required mobile breakpoint styling
-   [X] I completed any required hover state styling
-   [X] I included a working spec file
-   ~~[ ] I added notes above …
=> fix: APPS-3448 expect infoblock array, add heading

pages/index.vue
Connected to [APPS-3472](https://jira.library.ucla.edu/browse/APPS-3472)
**Page/Pages Created/updated:** pages/index.vue 
**Notes:**
Since the Now Showing section data is already being parsed, I just added a bit of logic to substitute the eventTitle for the title in this specific case. 
This took me less than an hour to build this.
**Checklist:**
-   [X] I completed any required mobile breakpoint styling
-   [X] I completed any required hover state styling
-   [X] I included a working spec file
-   [X] UX has reviewed this PR
[APPS-3472]: …
=> feat: APPS-3472 swap title for eventTitle in now showing section

gql/queries/FTVAEventSeriesList.gql, pages/series/index.vue
Connected to [APPS-3477](https://jira.library.ucla.edu/browse/APPS-3477)
This PR uses titleSort for ongoing series and removes the gql portion, which fetches event series from craft as we are using ES query to fetch event series records 
[APPS-3477]: https://uclalibrary.atlassian.net/browse/APPS-3477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: sort order for ongoing titles
