UCLALibrary/ftva-website-nuxt

- .github/workflows/ci.yml
- .github/workflows/percy.yml
- .github/workflows/production-site-build.yml
- .github/workflows/regenerate-site.yml
Connected to [APPS-2747](https://jira.library.ucla.edu/browse/APPS-2747)
Notes:
Now with any PRs, the workflows will run and perform tests
[APPS-2747]: https://uclalibrary.atlassian.net/browse/APPS-2747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Update github actions for percy, ci and other workfows for nuxt3 and ftva secret variables from github

- .github/workflows/production-site-build.yml
Connected to [APPS-2817](https://jira.library.ucla.edu/browse/APPS-2817)
[APPS-2817]: https://uclalibrary.atlassian.net/browse/APPS-2817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ci for production build

- .github/workflows/production-site-build.yml
Connected to [APPS-2838](https://jira.library.ucla.edu/browse/APPS-2838)
[APPS-2838]: https://uclalibrary.atlassian.net/browse/APPS-2838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: yaml syntax

- pages/events/index.vue
Connected to [APPS-2840](https://jira.library.ucla.edu/browse/APPS-2840)
[APPS-2840]: https://uclalibrary.atlassian.net/browse/APPS-2840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Add imports and fix uri, as we have added trailing slash to the urls now in component library

- gql/queries/FTVAEventDetail.gql
- pages/events/[slug].vue
Connected to [APPS-2848](https://uclalibrary.atlassian.net/browse/APPS-2848)
1. BlockInfo does NOT show when there is no info
2. Fixes the missing images in the EventSeries at the bottom of the page 
3. Makes all EventSeries same height
4. Fixes font size of EventSeries
[APPS-2848]: https://uclalibrary.atlassian.net/browse/APPS-2848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Page BlockInfo & EventSeries issues

- pages/events/[slug].vue
Connected to [APPS-2855](https://jira.library.ucla.edu/browse/APPS-2855)
Serena say that the min-width of the BlockInfo needs to be wide enough that The Billy Wilder theater is all on one line. About 282px wide.
[APPS-2855]: https://uclalibrary.atlassian.net/browse/APPS-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2855 Page Adjust the width of Sidebar 

- .github/workflows/ci.yml
- .github/workflows/percy.yml
- .github/workflows/production-site-build.yml
- .github/workflows/regenerate-site.yml
- nuxt.config.ts
- package.json
Connected to [APPS-2849](https://jira.library.ucla.edu/browse/APPS-2849)
These changes may fix following issues:
- https://github.com/UCLALibrary/ftva-website-nuxt/actions/runs/10153080705/job/28075736759#step:8:8451
- https://github.com/UCLALibrary/ftva-website-nuxt/actions/runs/10166900114/job/28118073275#step:5:46303
[APPS-2849]: https://uclalibrary.atlassian.net/browse/APPS-2849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2849

- .github/workflows/production-site-build.yml
- .github/workflows/regenerate-site.yml
- nuxt.config.ts
- package.json
- pages/events/[slug].vue
- pnpm-lock.yaml
Connected to [APPS-2866](https://jira.library.ucla.edu/browse/APPS-2866)
https://deploy-preview-15--test-ftva.netlify.app/events/la-r%C3%A9gion-centrale-03-08-24
1. Update component version to latest
2. Remove timeout from this workflow [ftva-website-nuxt/.github/workflows/production-site-build.yml at main · UCLALibrary/ftva-website-nuxt](https://github.com/UCLALibrary/ftva-website-nuxt/blob/main/.github/workflows/production-site-build.yml#L16) 
4. Remove time out from this workflow [ftva-website-nuxt/.github/workflows/regenerate-site.yml at main · UCLALibrary/ftva-website-nuxt](https://github.com/UCLALibrary/ftva-website-nuxt/blob/main/.github/workflows/regenerate-site.yml#L23) 
6. Update concurrency to 50 here [ftva-website-nuxt/nuxt.config.ts at main · …
> chore: APPS-2866 Update FTVA Nuxt with library component version 3.5.7

- pages/events/[slug].vue
Connected to [APPS-2883](https://uclalibrary.atlassian.net/browse/APPS-2883)
https://deploy-preview-18--test-ftva.netlify.app/events/la-r%C3%A9gion-centrale-03-08-24
[APPS-2883]: https://uclalibrary.atlassian.net/browse/APPS-2883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: APPS-2883 update section-title in on the EventDetail page in the SectionTeaserCard

- gql/queries/FTVAEventSeriesDetail.gql
Connected to [APPS-2921](https://jira.library.ucla.edu/browse/APPS-2921)
**Page updated:** FTVAEventSeriesDetail.gql
**Notes:**
- Add `sectionHandle` to ongoing series, upcoming series queries
**Checklist:**
-   [x] I requested a PR review from the dev team
-   ~[ ] I double checked it looks like the designs~
-   ~[ ] I completed any required mobile breakpoint styling~
-   ~[ ] I completed any required hover state styling~
-   ~[ ] I included a working spec file~
-   ~[ ] I added notes above about how long it took to build this component~
-   ~[ ] UX has reviewed this PR~
[APPS-2921]: https://uclalibrary.atlassian.net/browse/APPS-2921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2921 Update SeriesDetail query

- package.json
- pnpm-lock.yaml
- server/api/fetchNitroStorageCraftHeaderData.js
Connected to [APPS-2927](https://jira.library.ucla.edu/browse/APPS-2927)
**Notes:**
- Updated component library to new version: `3.12.0`
- Updated header data query
**Checklist:**
-   [x] I requested a PR review from the dev team
-   ~[ ] I double checked it looks like the designs~
-   ~[ ] I completed any required mobile breakpoint styling~
-   ~[ ] I completed any required hover state styling~
-   ~[ ] I included a working spec file~
-   ~[ ] I added notes above about how long it took to build this component~
-   ~[ ] UX has reviewed this PR~
[APPS-2927]: https://uclalibrary.atlassian.net/browse/APPS-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS 2927 Update Header query

- server/api/fetchNitroStorageCraftGlobalData.js
Connected to [APPS-3000](https://jira.library.ucla.edu/browse/APPS-3000)
**Page Updated:**
- /server/api/fetchNitroStorageCraftGlobalData.js
**Notes:**
- Update query
**Checklist:**
[APPS-3000]: https://uclalibrary.atlassian.net/browse/APPS-3000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: APPS-3000 Update FTVA Globals Query

- nuxt.config.ts
- pages/blog/[slug].vue
- pages/collections/[slug].vue
- pages/events/[slug].vue
- pages/series/[slug].vue
Connected to [APPS-2974](https://jira.library.ucla.edu/browse/APPS-2974) and [APPS-2964](https://jira.library.ucla.edu/browse/APPS-2964)
**Notes:**
APPS-2974
- updated package.json
- added useHead to all existing [slug].vue pages
APPS-2964
- remove '.' from end of text when no past or upcoming events
This took me 4ish hours to build this, including time to read the ticket and documentation.
**Checklist:**
-   ~~[] I completed any required mobile breakpoint styling~~
-   ~~[ ] UX has reviewed this …
> chore: APPS-2974 add title of entry as value for <title> tag in template

- composables/useHeader.js
- modules/init.js
- package.json
- pages/collections/[slug].vue
- pages/events/[slug].vue
- pages/series/[slug].vue
- plugins/craft-layout-data.client.js
- plugins/data-api.js
- plugins/indexer.server.js
- utils/arrayOfArrays.js
Connected to [APPS-3009](https://jira.library.ucla.edu/browse/APPS-3009)
**Notes:**
- updated heapsize from 8096 to 12288
- commented out `console` statements in the code
**Checklist:**
-   [x] I have requested a PR review from the Dev team
[APPS-3009]: https://uclalibrary.atlassian.net/browse/APPS-3009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-3009 Increase heapsize for production build

- app.vue
- layouts/default.vue
- modules/init.js
- nuxt.config.ts
- plugins/data-api.js
Connected to [APPS-3009](https://jira.library.ucla.edu/browse/APPS-3009)
**Notes:**
- Disable/comment out remaining active console statements
**Checklist:**
-   [x] I have requested a PR review from the Dev team
[APPS-3009]: https://uclalibrary.atlassian.net/browse/APPS-3009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Disable all console statements

- modules/finalize.js
- modules/init.js
Connected to [APPS-2938](https://jira.library.ucla.edu/browse/APPS-2938)
**Page/Pages Created/updated:** finalize.js from #APPS-2938
**Notes:**
I mostly copied the code from the ticket, which Parinita supplied.  
This took me 2ish hours to build this.
**Checklist:**
[APPS-2938]: https://uclalibrary.atlassian.net/browse/APPS-2938?atlOrigin=eyJpIjoiNWRk …
> feat: delete old es index when making new

- package.json
- pages/events/[slug].vue
- pages/series/[slug].vue
- pnpm-lock.yaml
Connected to [APPS-3039](https://jira.library.ucla.edu/browse/APPS-3039)
**Pages Updated:**
- pages/events/[slug].vue
- pages/series/[slug].vue
**Notes:**
- Updated component package to `3.31.4` to include spacing and breakpoint fixes in TwoColumn component
- Minor update to CSS on templates impacted by changes to the TwoCol component
**Previews:**
- https://deploy-preview-63--test-ftva.netlify.app/events/the-pink-cloud-shorts-03-02-24/
- https://deploy-preview-63--test-ftva.netlify.app/series/step-up-series
**Checklist:**
-   [x] I requested a PR review from the Dev team
-   ~~[ ] I completed any required hover state …
> fix: APPS-3039 update sidebar col breakpoint

- gql/queries/FTVAEventDetail.gql
- nuxt.config.ts
- package.json
- pages/blog/[slug].vue
- pages/events/[slug].vue
- pnpm-lock.yaml
Connected to:
+ [APPS-2976](https://jira.library.ucla.edu/browse/APPS-2976) - Category in CardMeta should link to the series entry on **EventDetail** page
+ [APPS-3011](https://jira.library.ucla.edu/browse/APPS-3011) - Move the about-author field out of CardMeta into a RichText component to fix truncation on the **BlogDetail** page 
---
The **category is now linkable** here:  
https://deploy-preview-61--test-ftva.netlify.app/events/la-r%C3%A9gion-centrale-03-08-24
Look for the **About the Author** here:
https://deploy-preview-61--test-ftva.netlify.app/blog/test-tom-reeds-for-members-only-black-perspectives-on-local-l-a-tv
---
**Notes:**
This is a two part PR. Updates are made in [ucla-library-website-components](https://github.com/UCLALibrary/ucla-library-website-components/pull/639) …
> fix: APPS-2976 & APPS-3011 updates to cardMeta - BlogDetail & EventDetail pages

- composables/useIndexAggregator.js
- pages/events/index.vue
Connected to [APPS-3024](https://jira.library.ucla.edu/browse/APPS-3024)
**Page updated:** /events/index.vue
**Notes:**
- Created a useIndexAggregator composable that will return a list of tags for events
- Implemented this aggregator on the page
This took me 6ish hours so far to build this, mostly reading documentation, looking at existing example in the library nuxt site, and testing the query on kibana
**Checklist:**
-   ~~ I double checked it looks like the designs~~
-   ~~I completed any required mobile breakpoint styling~~
-   ~~I completed any required hover state styling~~
-   [X] I included a working spec file
-   ~~UX has reviewed this …
> feat: APPS-3024 es query for tags

- app.vue
- error.vue
- layouts/default.vue
- modules/init.js
- nuxt.config.ts
- plugins/indexer.server.js
Connected to [APPS-3061](https://jira.library.ucla.edu/browse/APPS-3061)
Add  ftva routes to nuxt.config from craft. Replace process.env with import.meta.dev or import.meta.env
[APPS-3061]: https://uclalibrary.atlassian.net/browse/APPS-3061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Add routes and use import.meta

- composables/useCalendarSearchFilter.js
- composables/useDateFilterQuery.js
- composables/useListSearchFilter.js
- pages/events/index.vue
Connected to [APPS-3085](https://jira.library.ucla.edu/browse/APPS-3085)
Connected to [APPS-3086](https://jira.library.ucla.edu/browse/APPS-3086)
**Notes:**
1. Fix images in the list view
2. Separate ES query for list and calendar view in different composables
3.  Add initial-tab to tablist component based on view query param
[APPS-3085]: https://uclalibrary.atlassian.net/browse/APPS-3085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPS-3086]: https://uclalibrary.atlassian.net/browse/APPS-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3085 APPS-3086 update and refactor ES code for different views and Date filter

- composables/useContentIndexer.js
- composables/useListSearchFilter.js
- modules/finalize.js
- modules/init.js
- package.json
- pages/events/index.vue
- pages/series/index.vue
- pnpm-lock.yaml
Connected to [APPS-3076](https://jira.library.ucla.edu/browse/APPS-3076)
**Page/Pages Created/updated:** {/event/index}.vue 
**Notes:**
1. Add vueUse to use a different layout for mobile screens
2. Add typescript -> Can improve more by adding types for ES results object
3. Verify datefilter and dropdownfilters from URL with ES search
4.  Additional styling will be added in another ticket, Also next, I will be working on adding infinite scrolling to this mobile layout.
5. commented out console.logs
4 to 5 hours
[APPS-3076]: https://uclalibrary.atlassian.net/browse/APPS-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3076 Add typescript and SectionRemoveSearchFilters

- composables/useListSearchFilter.js
- pages/events/index.vue
- utils/getEventFilterLabels.js
Connected to [APPS-3102](https://jira.library.ucla.edu/browse/APPS-3102)
Notes:
This PR adds vueuse infinite scroll composable for mobile screens
[APPS-3102]: https://uclalibrary.atlassian.net/browse/APPS-3102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add vue use infinitescroll composable for mobile screens

- package.json
- pages/events/index.vue
- pnpm-lock.yaml
- utils/getEventFilterLabels.js
Connected to [APPS-3078](https://jira.library.ucla.edu/browse/APPS-3078)
**Page/Pages Created/updated:** events/index.vue from #3078
**Notes:**
- I updated the component & token libraries
- I updated the util file for events to make it aware of the isHighlighted field
- I uncommented the Filters Dropdown component and hooked it up enough to test the highlighted filters
- I moved the filter components into the slot the tabList component has for them 
This took probably 8 hours to build & test, mostly because of dependencies and how it needs to be hooked into everything else (route, es query, etc)
**Checklist:**
-   ~~[ ] …
> feat: APPS-3078 add highlight logic for filters

- package.json
**Notes:**
Quick fix because release is failing due to memory heap size errors!
> fix: increase node memory size

- gql/queries/FTVAEventSeriesDetail.gql
- pages/events/index.vue
- pages/series/index.vue
Connected to [APPS-3111](https://jira.library.ucla.edu/browse/APPS-3111)
[APPS-3111]: https://uclalibrary.atlassian.net/browse/APPS-3111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3111 Add infinite scrolling for mobile screens for series listing page

- cypress/e2e/eventListPage.cy.js
- package.json
- pages/events/index.vue
- pnpm-lock.yaml
Connected to [APPS-3051](https://jira.library.ucla.edu/browse/APPS-3051)
**Page updated:** pages/events/index.vue
**Preview:** https://deploy-preview-87--test-ftva.netlify.app/events/
**Notes:**
- Moved DateFilter and FiltersDropdown components into TabList slot
- Template code currently is duplicating `SectionTeaserList, DateFilter and FiltersDropdown` components in the desktop and mobile states
- I attempted a refactor to use a single instance of the three components all within the TabList component; conditionally rendering the calendar view tab and removing the `mobile-container` template logic, but this ended up breaking the InfiniteScroll functionality and revealed a potential bug with the TabList component:
- On page load on mobile, code throws a 500 error because the calendar view …
> feat: APPS-3051 Update Event Index Styling

- gql/queries/FTVAArticleDetail.gql
- gql/queries/FTVAArticleList.gql
- pages/blog/index.vue
Connected to [APPS-3108](https://jira.library.ucla.edu/browse/APPS-3108)
**Page updated:** /pages/blog/index.vue
**Notes:**
- Added GraphQL query for Article Listing page
- Updated Article Detail query with listing image field
- Loaded preformatted data for testing
**Preview:** https://deploy-preview-95--test-ftva.netlify.app/blog/
**Checklist:**
-   [x] I requested a PR review from the Dev team
[APPS-3108]: …
> feat: APPS 3108 Add Article Listing GQL query

- nuxt.config.ts
- package.json
- pages/events/index.vue
- pages/series/index.vue
- pnpm-lock.yaml
Connected to [APPS-3118](https://jira.library.ucla.edu/browse/APPS-3118)
**Page/Pages Created/updated:** `series/index.vue `
**Page/Pages Created/updated:** `events/index.vue `
[APPS-3118]: https://uclalibrary.atlassian.net/browse/APPS-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: APPS-3118

- error.vue
- gql/queries/FTVACollectionItem.gql
- pages/collections/[collectionSlug]/[slug].vue
Connected to [APPS-3141](https://jira.library.ucla.edu/browse/APPS-3141)
**Page Created:** pages / collections / [collectionSlug] / [slug].vue
**Notes:**
- Added GraphQL query for Collection Item Details page
- Loaded preformatted data for testing
**Previews:** 
- https://deploy-preview-110--test-ftva.netlify.app/collections/la-rebellion/grey-area
- https://deploy-preview-110--test-ftva.netlify.app/collections/la-rebellion/finding-buck-mchenry
- https://deploy-preview-110--test-ftva.netlify.app/collections/archive-event-audio-recordings/test-collection-item-for-archive-events-audio-recordings-2-2-2-2
**Checklist:**
-  [x] I added github label for semantic versioning
-  [x] I requested a PR review from the Dev team
-   ~~[ ] I …
> feat: APPS 3141 Add Collection Item Detail query

- app.vue
- error.vue
- gql/fragments/BlockCardWithImageFragment.gql
- gql/fragments/collections/AllFtvaFpb.gql
- gql/queries/FTVAArticleDetail.gql
- layouts/default.vue
- nuxt.config.ts
- package.json
- pages/[...slug].vue
- pages/blog/[slug].vue
- pages/blog/index.vue
- pages/collections/[collectionSlug]/[slug].vue
- pages/collections/[slug].vue
- pages/collections/index.vue
- pages/collections/la-rebellion/filmmakers/[slug].vue
- pages/collections/la-rebellion/filmmakers/index.vue
- pages/events/[slug].vue
- pages/events/index.vue
- pages/series/[slug].vue
- pages/series/index.vue
- plugins/add-library-website-vue-components.js
- pnpm-lock.yaml
Connected to [APPS-3230](https://jira.library.ucla.edu/browse/APPS-3230)
[APPS-3230]: https://uclalibrary.atlassian.net/browse/APPS-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3230 update the allftva fpb query to include card with image

- cypress/e2e/billyWilderTheater.cy.js
- gql/queries/BillyWilderTheater.gql
- pages/billy-wilder-theater/index.vue
Connected to [APPS-3240](https://jira.library.ucla.edu/browse/APPS-3240)
**Page Updated:** /pages/billy-wilder-theater/index.vue
**Notes:**
- Assembled page template with components
- Added basic Cypress testing
- Slight updates to the gql query
**Preview:** https://deploy-preview-122--test-ftva.netlify.app/billy-wilder-theater
**Checklist:**
-   [x] UX has reviewed this PR
-   [x] I have requested a PR review from the Dev team
[APPS-3240]: …
> feat: APPS-3240 Assemble Billy Wilder page

- app.vue
- composables/useContentIndexer.js
- error.vue
- layouts/default.vue
- nuxt.config.ts
- package.json
- pages/[...slug].vue
- pages/archive-research-study-center/index.vue
- pages/billy-wilder-theater/index.vue
- pages/blog/[slug].vue
- pages/blog/index.vue
- pages/collections/[collectionSlug]/[slug].vue
- pages/collections/[slug].vue
- pages/collections/index.vue
- pages/collections/la-rebellion/filmmakers/[slug].vue
- pages/collections/la-rebellion/filmmakers/index.vue
- pages/events/[slug].vue
- pages/events/index.vue
- pages/series/[slug].vue
- pages/series/index.vue
- plugins/add-vue-skip-to.js
- pnpm-lock.yaml
Connected to [APPS-3261](https://jira.library.ucla.edu/browse/APPS-3261)
Also removed vue-skip-to package as it never worked in Nuxt3
[APPS-3261]: https://uclalibrary.atlassian.net/browse/APPS-3261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: use component librray nuxt module with auto imports, remove auto imports and disable crawler, add all the routes to routes array in nuxt.config

- nuxt.config.ts
No ticket, loosely related to https://uclalibrary.atlassian.net/browse/APPS-3264
https://nuxt.com/docs/guide/going-further/features#inlinestyles
**Page/Pages Created/updated:** {filename}.vue from #{issue number}
**Notes:**
Possible fix for large page sizes due to tons of inline'd css. 
In tests this cut page index.vue routes by 50%. 
This took me {x} hours to build this.
**Checklist:**
-   [ ] I added github label for semantic versioning
-   [ ] I double checked it looks like the designs
-   [ ] I completed any required mobile breakpoint styling
-   [ ] I completed any required hover state styling
-   [ ] I added notes above about how long it took to build this component
-   [ ] UX has reviewed this PR
-   [ ] I assigned this PR to …
> feat: remove duplicate styles

- package.json
- pages/blog/[slug].vue
- pages/collections/[collectionSlug]/[slug].vue
- pages/collections/[slug].vue
- pages/events/[slug].vue
- pages/series/[slug].vue
- pnpm-lock.yaml
Connected to [APPS-3303](https://jira.library.ucla.edu/browse/APPS-3303)
**Notes:**
- Updated `SectionTeaserCard` components with new `gridLayout` prop to retain horizontal scroll
- See related component PR: [APPS-3291](https://github.com/UCLALibrary/ucla-library-website-components/pull/724)
- Updated component-library-nuxt-modules to `1.2.7`
**Page Updated:**
- pages/blog/[slug].vue
- https://deploy-preview-142--test-ftva.netlify.app/blog/archival-ethics
- pages/collection/[slug].vue
- https://deploy-preview-142--test-ftva.netlify.app/collections/test-get-used-to-it
- pages/collection/[collectionSlug]/[slug].vue
- https://deploy-preview-142--test-ftva.netlify.app/collections/la-rebellion/grey-area 
- pages/event/[slug].vue
- https://deploy-preview-142--test-ftva.netlify.app/events/step-up …
> fix: APPS-3303 Add gridLayout prop to SectionTeaserCards

- package.json
- pages/collections/la-rebellion/filmmakers/index.vue
- pnpm-lock.yaml
Notes:
Next step test this on the Main Library Website
> feat: Add useRoute and update component version to add the fix for alphabetical browseby

- components/BasicCollection.vue
- components/ListOfItemsCollection.vue
- composables/useCollectionListSearch.js
- gql/queries/FTVACollectionType.gql
- modules/init.js
- pages/collections/[collectionSlug]/[slug].vue
- pages/collections/motion-picture/index.vue
- utils/normalizeTitleForAlphabeticalBrowseBy.ts
Ignore articles at the start of title when browsing by alphabet.
https://deploy-preview-154--test-ftva.netlify.app/collections/motion-picture?filters=S
https://deploy-preview-154--test-ftva.netlify.app/collections/motion-picture?filters=W
> feat: Replace wildcard search with prefix query and add a new field to remove article from title and use it for Alphabetical browse

- cypress/e2e/homepage.cy.js
- gql/queries/FTVAHomepage.gql
- package.json
- pages/blog/index.vue
- pages/collections/la-rebellion/filmmakers/index.vue
- pages/collections/la-rebellion/filmography/index.vue
- pages/index.vue
- pnpm-lock.yaml
- utils/formatEventDates.js
- utils/formatEventSeriesDates.js
Connected to [APPS-3372](https://jira.library.ucla.edu/browse/APPS-3372)
**Page updated:** /pages/index.vue
**Notes:**
- Assembled components for homepage template
- Updated GraphQL queries/fields
- Implemented CSS updates
- Added Cypress test
- Updated Nuxt modules
- Clean up console statements in other page templates per Github Actions warnings
**Preview:** https://deploy-preview-177--test-ftva.netlify.app/
**Checklist:**
-   [x] UX has reviewed this …
> feat: APPS-3372 Assemble FTVA Homepage Components

- composables/useMobileOnlyInfiniteScroll.ts
- composables/useSiteSearch.ts
- layouts/default.vue
- package.json
- pages/events/index.vue
- pages/search.vue
- pnpm-lock.yaml
- utils/parseFilters.js
- utils/parseImage.js
Connected to [APPS-3377](https://jira.library.ucla.edu/browse/APPS-3377)
The error page when on the test environment will be slow to load if not on vpn.
The dates on the small screen sometimes overlap with the description if the title or description is more than 2 lines.
The component package version is latest on this PR
[APPS-3377]: https://uclalibrary.atlassian.net/browse/APPS-3377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3377 update search

- package.json
- pnpm-lock.yaml
**Notes:**
update component and design token package
> feat: update component and design token package

- components/ListOfItemsCollection.vue
- package.json
- pages/blog/index.vue
- pages/collections/la-rebellion/filmmakers/index.vue
- pages/collections/motion-picture/index.vue
- pages/search.vue
- pages/series/index.vue
- pnpm-lock.yaml
Connected to [APPS-3411](https://jira.library.ucla.edu/browse/APPS-3411)
**Notes:**
- Updated all use of SectionPagination component with new props from component updates in [APPS-3187](https://github.com/UCLALibrary/ucla-library-website-components/pull/780),  [APPS-3414](https://github.com/UCLALibrary/ucla-library-website-components/pull/796)
- Moved search pagination into one-column layout
- Updated Nuxt modules package to 1.2.55
https://deploy-preview-199--test-ftva.netlify.app/blog/
https://deploy-preview-199--test-ftva.netlify.app/search?q=love
https://deploy-preview-199--test-ftva.netlify.app/collections/la-rebellion/filmmakers/
https://deploy-preview-199--test-ftva.netlify.app/collections/la-rebellion/filmography
https://deploy-preview-199--test-ftva.netlify.app/collections/motion-p …
> fix: APPS 3411 Update page pagination

- pages/search.vue
Connected to [APPS-3434](https://jira.library.ucla.edu/browse/APPS-3434)
**Page/Pages Created/updated:** search.vue from 
**Notes:**
Fixed no results text to desired text
This took me 1 hours to build this.
**Links:**
https://deploy-preview-211--test-ftva.netlify.app/search?q=asdf
**Photos:**
Before:
After:
**Checklist:**
-   [x] I completed any required hover state styling
-   [x] I added notes above about how long it took to build this component
-   [ ] UX has reviewed this PR
[APPS-3434]: …
> fix: APPS-3434 update search results no results text

- .github/workflows/lint-pr.yml
- package.json
- pnpm-lock.yaml
Connected to [APPS-3395](https://jira.library.ucla.edu/browse/APPS-3395)
**Page/Pages Created/updated:** package.json from
**Notes:**
Update Component library version
This took me {x} hours to build this.
**Checklist:**
-   [ ] I double checked it looks like the designs
-   [ ] I completed any required mobile breakpoint styling
-   [ ] I completed any required hover state styling
-   [ ] I added notes above about how long it took to build this component
-   [ ] UX has reviewed this PR
[APPS-3395]: https://uclalibrary.atlassian.net/browse/APPS-3395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> fix: update components library in package.json

- pages/collections/la-rebellion/index.vue
Connected to [APPS-3443](https://jira.library.ucla.edu/browse/APPS-3443)
**Page/Pages Created/updated:** collections/la-rebellion/index.vue
**Notes:**
This took me 2 hours to build this.
**Checklist:**
-   [X] I completed any required mobile breakpoint styling
-   [X] I completed any required hover state styling
-   [X] I included a working spec file
-   [X] UX has reviewed this PR
[APPS-3443]: https://uclalibrary.atlassian.net/browse/APPS-3443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:  APPS-3443 heading showing without content

- package.json
- pages/[...slug].vue
- pages/archive-research-study-center.vue
- pages/blog/[slug].vue
- pages/collections/la-rebellion/index.vue
- pnpm-lock.yaml
Connected to [APPS-3031](https://jira.library.ucla.edu/browse/APPS-3031)
1. Add ftva-fpb-rich-text-h3 ftva-fpb-rich-text-h4 & ftva-fpb-rich-text-h5 to slug pages
2. Update design-token package
---
1. `[…slug].vue pages`
2. `archive-research-study-center.vue`
3. `[slug].view pages/blog`
4. `index.vue pages/collections/la-rebellion`
These are the styles that are being pulled from the [Design Token Library](https://github.com/UCLALibrary/design-tokens/pull/158/files)
```
// Flexible Page Block RichText Headings
@mixin ftva-fpb-rich-text-h3 {
font-family: $font-primary;
font-size: 36px;
font-weight: $font-weight-regular;
line-height: 110%;
}
@mixin ftva-fpb-rich-text-h4 {
font-family: $font-primary;
font-size: 28px;
font-weight: $font-weight-medium;
line-height: 110%;
}
@mixin …
```
> feat: APPS-3442 Update h3,h4, h5 tags fpb richtext
